//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714CRajekex2h
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChurchAppModelContainer : DbContext
    {
        public ChurchAppModelContainer()
            : base("name=ChurchAppModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<BusinessTransaction> BusinessTransactions { get; set; }
        public virtual DbSet<Church> Churches { get; set; }
        public virtual DbSet<Doner> Doners { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Pastor> Pastors { get; set; }
        public virtual DbSet<TransationType> TransationTypes { get; set; }
        public virtual DbSet<PotentialMember> PotentialMembers { get; set; }
    }
}
