//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714CRajekex2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class PotentialMembers
    {
        public int Id { get; set; }
        public string DateOfContact { get; set; }
    }
}
