****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ApartmentId]
      ,[BuildingId]
      ,[ApartmentNum]
      ,[SquareFeet]
      ,[Bathrooms]
      ,[Rent]
      ,[TenantId]
      ,[AdminId]
  FROM [PropertyManager].[dbo].[Apartment]